/*
*** MADE BY MITHION'S .SCHEMATIC TO JAVA CONVERTING TOOL v1.6 ***
*/

package com.salvestrom.w2theJungle.worldGen.structures.jungleTown;
import java.util.Random;

import com.salvestrom.w2theJungle.init.JungleBlocks;
import com.salvestrom.w2theJungle.worldGen.biome.JungleBiomeRegistry;
import com.salvestrom.w2theJungle.worldGen.structures.blockPlacmentBridge;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.BiomeJungle;
import net.minecraft.world.gen.feature.WorldGenerator;

public class jungleBaskingArea extends WorldGenerator
{
	public blockPlacmentBridge bridge = new blockPlacmentBridge();

	protected Block[] GetValidSpawnBlocks() {
		return new Block[] {
			Blocks.GRASS,
			Blocks.STONE,
			Blocks.DIRT,
		};
	}

	public boolean LocationIsValidSpawn(World world, int i, int j, int k)
	{
		/*
		int distanceToAir = 0;
		Block checkID = world.getBlock(i, j, k);

		if (checkID != Blocks.AIR){
			distanceToAir++;
			checkID = world.getBlock(i, j + distanceToAir, k);
		}

		if (distanceToAir > 5){
			return false;
		}
		j += distanceToAir - 1;

		Block blockID = world.getBlock(i, j, k);
		Block blockIDAbove = world.getBlock(i+5, j+1, k+5);
		Block blockIDBelow = world.getBlock(i, j-1, k);
		for (Block x : GetValidSpawnBlocks()){
			if (blockIDAbove != Blocks.AIR){
				return false;
			}
//			if (blockID == x){
//				return true;
//			}
		else if (blockID == Blocks.snow && blockIDBelow == x){
				return true;
			}
		}
	*/
		return true;
	}

	public jungleBaskingArea() { }

	public boolean generate(World world, Random rand, int i, int j, int k) {
		//check that each corner is one of the valid spawn blocks
		//if(!LocationIsValidSpawn(world, i+1, j, k+1) || !LocationIsValidSpawn(world, i + 9, j, k+1) || !LocationIsValidSpawn(world, i+9, j, k+9) || !LocationIsValidSpawn(world, i+1, j, k+9))
		//if(world.getBlock(i+5,  j+1, k+5) != Blocks.AIR || world.getBlock(i+5,  j+2, k+5) != Blocks.AIR)
		//{			return false;		}
		Biome bio = world.getBiome(new BlockPos(i+5, 0, k+5));
		
		if(bio != JungleBiomeRegistry.biomeJungleSwamp || !(bio instanceof BiomeJungle)) {
			return false;
		}
			
		bridge.setBlock(world, i + 0, j + 0, k + 0, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 0, j + 0, k + 1, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 0, j + 0, k + 2, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 0, j + 0, k + 3, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 0, j + 0, k + 4, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 0, j + 0, k + 5, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 0, j + 0, k + 6, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 0, j + 0, k + 7, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 0, j + 0, k + 8, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 0, j + 0, k + 9, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 0, j + 0, k + 10, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 0, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 0, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 0, k + 0, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 1, j + 0, k + 1, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 1, j + 0, k + 2, Blocks.DIRT);
		bridge.setBlock(world, i + 1, j + 0, k + 3, Blocks.DIRT);
		bridge.setBlock(world, i + 1, j + 0, k + 4, Blocks.DIRT);
		bridge.setBlock(world, i + 1, j + 0, k + 5, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 1, j + 0, k + 6, Blocks.DIRT);
		bridge.setBlock(world, i + 1, j + 0, k + 7, Blocks.DIRT);
		bridge.setBlock(world, i + 1, j + 0, k + 8, Blocks.DIRT);
		bridge.setBlock(world, i + 1, j + 0, k + 9, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 1, j + 0, k + 10, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 1, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 1, k + 1, JungleBlocks.jungleBrazier);
		bridge.setBlock(world, i + 1, j + 1, k + 2, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 1, j + 1, k + 3, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 1, j + 1, k + 4, JungleBlocks.mossyStoneSteps);
		bridge.setBlock(world, i + 1, j + 1, k + 5, JungleBlocks.mossyStoneSteps);
		bridge.setBlock(world, i + 1, j + 1, k + 6, JungleBlocks.mossyStoneSteps);
		bridge.setBlock(world, i + 1, j + 1, k + 7, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 1, j + 1, k + 8, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 1, j + 1, k + 9, JungleBlocks.jungleBrazier);
		bridge.setBlock(world, i + 1, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 1, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 0, k + 0, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 2, j + 0, k + 1, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 2, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 3, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 4, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 5, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 6, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 7, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 8, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 9, Blocks.DIRT);
		bridge.setBlock(world, i + 2, j + 0, k + 10, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 2, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 1, k + 1, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 2, j + 1, k + 2, Blocks.GRASS);
		bridge.setBlock(world, i + 2, j + 1, k + 3, Blocks.GRASS);
		bridge.setBlock(world, i + 2, j + 1, k + 4, Blocks.GRASS);
		bridge.setBlock(world, i + 2, j + 1, k + 5, Blocks.GRASS);
		bridge.setBlock(world, i + 2, j + 1, k + 6, Blocks.GRASS);
		bridge.setBlock(world, i + 2, j + 1, k + 7, Blocks.GRASS);
		bridge.setBlock(world, i + 2, j + 1, k + 8, Blocks.GRASS);
		bridge.setBlock(world, i + 2, j + 1, k + 9, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 2, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 2, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 0, k + 0, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 3, j + 0, k + 1, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 2, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 3, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 4, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 5, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 6, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 7, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 8, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 9, Blocks.DIRT);
		bridge.setBlock(world, i + 3, j + 0, k + 10, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 3, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 1, k + 1, JungleBlocks.mossystairs, 2, 2);
		bridge.setBlock(world, i + 3, j + 1, k + 2, Blocks.GRASS);
		bridge.setBlock(world, i + 3, j + 1, k + 3, Blocks.GRASS);
		bridge.setBlock(world, i + 3, j + 1, k + 4, Blocks.GRASS);
		bridge.setBlock(world, i + 3, j + 1, k + 5, Blocks.GRASS);
		bridge.setBlock(world, i + 3, j + 1, k + 6, Blocks.GRASS);
		bridge.setBlock(world, i + 3, j + 1, k + 7, Blocks.GRASS);
		bridge.setBlock(world, i + 3, j + 1, k + 8, Blocks.GRASS);
		bridge.setBlock(world, i + 3, j + 1, k + 9, JungleBlocks.mossystairs, 3, 2);
		bridge.setBlock(world, i + 3, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 3, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 0, k + 0, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 4, j + 0, k + 1, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 2, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 3, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 4, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 5, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 6, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 7, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 8, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 9, Blocks.DIRT);
		bridge.setBlock(world, i + 4, j + 0, k + 10, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 4, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 1, k + 1, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 4, j + 1, k + 2, Blocks.GRASS);
		bridge.setBlock(world, i + 4, j + 1, k + 3, Blocks.GRASS);
		bridge.setBlock(world, i + 4, j + 1, k + 4, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 4, j + 1, k + 5, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 4, j + 1, k + 6, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 4, j + 1, k + 7, Blocks.GRASS);
		bridge.setBlock(world, i + 4, j + 1, k + 8, Blocks.GRASS);
		bridge.setBlock(world, i + 4, j + 1, k + 9, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 4, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 4, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 0, k + 0, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 5, j + 0, k + 1, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 2, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 3, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 4, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 5, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 6, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 7, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 8, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 9, Blocks.DIRT);
		bridge.setBlock(world, i + 5, j + 0, k + 10, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 5, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 1, k + 1, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 5, j + 1, k + 2, Blocks.GRASS);
		bridge.setBlock(world, i + 5, j + 1, k + 3, Blocks.GRASS);
		bridge.setBlock(world, i + 5, j + 1, k + 4, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 5, j + 1, k + 5, Blocks.GLOWSTONE);
		bridge.setBlock(world, i + 5, j + 1, k + 6, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 5, j + 1, k + 7, Blocks.GRASS);
		bridge.setBlock(world, i + 5, j + 1, k + 8, Blocks.GRASS);
		bridge.setBlock(world, i + 5, j + 1, k + 9, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 5, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 5, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 0, k + 0, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 0, k + 1, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 6, j + 0, k + 2, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 0, k + 3, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 6, j + 0, k + 4, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 0, k + 5, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 0, k + 6, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 0, k + 7, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 6, j + 0, k + 8, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 0, k + 9, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 6, j + 0, k + 10, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 1, k + 1, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 1, k + 2, Blocks.GRASS);
		bridge.setBlock(world, i + 6, j + 1, k + 3, Blocks.GRASS);
		bridge.setBlock(world, i + 6, j + 1, k + 4, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 6, j + 1, k + 5, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 1, k + 6, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 6, j + 1, k + 7, Blocks.GRASS);
		bridge.setBlock(world, i + 6, j + 1, k + 8, Blocks.GRASS);
		bridge.setBlock(world, i + 6, j + 1, k + 9, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 6, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 6, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 0, k + 0, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 7, j + 0, k + 1, Blocks.GRASS);
		bridge.setBlock(world, i + 7, j + 0, k + 2, Blocks.DIRT);
		bridge.setBlock(world, i + 7, j + 0, k + 3, Blocks.DIRT);
		bridge.setBlock(world, i + 7, j + 0, k + 4, Blocks.DIRT);
		bridge.setBlock(world, i + 7, j + 0, k + 5, Blocks.DIRT);
		bridge.setBlock(world, i + 7, j + 0, k + 6, Blocks.DIRT);
		bridge.setBlock(world, i + 7, j + 0, k + 7, Blocks.DIRT);
		bridge.setBlock(world, i + 7, j + 0, k + 8, Blocks.DIRT);
		bridge.setBlock(world, i + 7, j + 0, k + 9, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 7, j + 0, k + 10, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 7, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 1, k + 1, JungleBlocks.mossystairs, 2, 2);
		bridge.setBlock(world, i + 7, j + 1, k + 2, Blocks.GRASS);
		bridge.setBlock(world, i + 7, j + 1, k + 3, Blocks.GRASS);
		bridge.setBlock(world, i + 7, j + 1, k + 4, Blocks.GRASS);
		bridge.setBlock(world, i + 7, j + 1, k + 5, Blocks.GRASS);
		bridge.setBlock(world, i + 7, j + 1, k + 6, Blocks.GRASS);
		bridge.setBlock(world, i + 7, j + 1, k + 7, Blocks.GRASS);
		bridge.setBlock(world, i + 7, j + 1, k + 8, Blocks.GRASS);
		bridge.setBlock(world, i + 7, j + 1, k + 9, JungleBlocks.mossystairs, 3, 2);
		bridge.setBlock(world, i + 7, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 7, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 0, k + 0, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 8, j + 0, k + 1, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 2, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 3, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 4, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 5, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 6, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 7, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 8, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 9, Blocks.DIRT);
		bridge.setBlock(world, i + 8, j + 0, k + 10, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 8, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 1, k + 1, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 8, j + 1, k + 2, Blocks.GRASS);
		bridge.setBlock(world, i + 8, j + 1, k + 3, Blocks.GRASS);
		bridge.setBlock(world, i + 8, j + 1, k + 4, Blocks.GRASS);
		bridge.setBlock(world, i + 8, j + 1, k + 5, Blocks.GRASS);
		bridge.setBlock(world, i + 8, j + 1, k + 6, Blocks.GRASS);
		bridge.setBlock(world, i + 8, j + 1, k + 7, Blocks.GRASS);
		bridge.setBlock(world, i + 8, j + 1, k + 8, Blocks.GRASS);
		bridge.setBlock(world, i + 8, j + 1, k + 9, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 8, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 8, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 0, k + 0, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 9, j + 0, k + 1, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 9, j + 0, k + 2, Blocks.DIRT);
		bridge.setBlock(world, i + 9, j + 0, k + 3, Blocks.GRASS);
		bridge.setBlock(world, i + 9, j + 0, k + 4, Blocks.DIRT);
		bridge.setBlock(world, i + 9, j + 0, k + 5, Blocks.DIRT);
		bridge.setBlock(world, i + 9, j + 0, k + 6, Blocks.DIRT);
		bridge.setBlock(world, i + 9, j + 0, k + 7, Blocks.GRASS);
		bridge.setBlock(world, i + 9, j + 0, k + 8, Blocks.DIRT);
		bridge.setBlock(world, i + 9, j + 0, k + 9, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 9, j + 0, k + 10, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 9, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 1, k + 1, JungleBlocks.jungleBrazier);
		bridge.setBlock(world, i + 9, j + 1, k + 2, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 9, j + 1, k + 3, JungleBlocks.mossystairs, 1, 2);
		bridge.setBlock(world, i + 9, j + 1, k + 4, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 9, j + 1, k + 5, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 9, j + 1, k + 6, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 9, j + 1, k + 7, JungleBlocks.mossystairs, 1, 2);
		bridge.setBlock(world, i + 9, j + 1, k + 8, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 9, j + 1, k + 9, JungleBlocks.jungleBrazier);
		bridge.setBlock(world, i + 9, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 9, j + 4, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 0, k + 0, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 10, j + 0, k + 1, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 10, j + 0, k + 2, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 10, j + 0, k + 3, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 10, j + 0, k + 4, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 10, j + 0, k + 5, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 10, j + 0, k + 6, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 10, j + 0, k + 7, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 10, j + 0, k + 8, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 10, j + 0, k + 9, Blocks.MOSSY_COBBLESTONE);
		bridge.setBlock(world, i + 10, j + 0, k + 10, Blocks.STONEBRICK, 1, 2);
		bridge.setBlock(world, i + 10, j + 1, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 1, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 2, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 3, k + 10, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 0, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 1, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 2, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 3, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 4, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 5, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 6, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 7, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 8, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 9, Blocks.AIR);
		bridge.setBlock(world, i + 10, j + 4, k + 10, Blocks.AIR);

		return true;
	}
	
	@Override
	public boolean generate(World wrld, Random rnd, BlockPos pos) {

		int x = pos.getX();
		int y = pos.getY();
		int z = pos.getZ();
		
		return this.generate(wrld, rnd, x, y, z);
	}
}